name: strings
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^3.0.0
  intl: ^0.16.0
  json_annotation: ^2.0.0
  path_provider: ^1.5.1
  encrypt: ^4.0.0
  audioplayers: ^0.14.0
  flutter_svg: 0.17.3+1
  flutter_picker: ^1.1.3
  shared_preferences: ^0.5.6+3
  flutter_section_table_view: ^1.0.5
  charts_flutter: ^0.9.0
  matrix_gesture_detector: ^0.1.0

dev_dependencies:
  intl_translation: ^0.17.9
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.3

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: NoteFont
      fonts:
        - asset: fonts/Puritan-Bold.ttf
    - family: LabelFont
      fonts:
        - asset: fonts/OxygenMono-Regular.ttf
    - family: LogoFont
      fonts:
        - asset: fonts/Fely.ttf

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon2048.png"